spring.application.name=system
# Database configuration
spring.datasource.url=postgresql://postgres:A12f-Dd326aBg4D46ad1dgbGdaf*1eb5@yamanote.proxy.rlwy.net:41688/railway
-
spring.datasource.username=postgres
spring.datasource.password=A12f-Dd326aBg4D46ad1dgbGdaf*1eb5
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size = -1
spring.servlet.multipart.max-request-size=-1
# Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.devtools.restart.enabled=true
server.port=8080
 spring.mail.host=smtp.gmail.com
 spring.mail.port=587
 spring.mail.username=etsayhaben@gmail.com
 spring.mail.password=zqes pron kruk fkcj
 spring.mail.properties.mail.smtp.auth=true
 spring.mail.properties.mail.smtp.starttls.enable=true
 spring.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:public/images/
 spring.security.user.password=demo@123
 spring.security.user.name=demo
 spring.datasource.hikari.maximum-pool-size=10
 spring.datasource.hikari.minimum-idle=2
 spring.datasource.hikari.idle-timeout=60000
 spring.datasource.hikari.connection-timeout=30000
admin.email=etsayhaben@gmail.com
admin.studentId=main58787012
admin.password=12345678

